language: python
sudo: false
cache: pip
python:
  - "3.5"
install:
  - pip install -U pip wheel
  - pip install -r tests/requirements.txt
  - python setup.py install
# command to run tests, e.g. python setup.py test
script: "cd tests && ./manage.py test testapp"
