language: python
python:
  - "2.7"
env:
  - DJANGO_VERSION=1.7
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install -q -r tests/requirements.txt --use-mirrors
  - python setup.py -q install
# command to run tests, e.g. python setup.py test
script: "cd tests && ./manage.py test testapp"
