language: python
sudo: false
python:
  - "2.7"
env:
  - DJANGO_VERSION=1.9.1
install:
  - pip install -q -r tests/requirements.txt
  - python setup.py -q install
# command to run tests, e.g. python setup.py test
script: "cd tests && ./manage.py test testapp"
