# Generated by Django 2.0.3 on 2018-03-06 17:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("zivinetz", "0001_initial")]

    operations = [
        migrations.RemoveField(model_name="waitlist", name="drudge"),
        migrations.RemoveField(model_name="waitlist", name="specification"),
        migrations.AlterField(
            model_name="assignmentchange",
            name="changed_by",
            field=models.CharField(
                default="nobody", max_length=100, verbose_name="changed by"
            ),
        ),
        migrations.AlterField(
            model_name="drudge",
            name="motor_saw_course",
            field=models.CharField(
                blank=True,
                choices=[("2-day", "2 day course"), ("5-day", "5 day course")],
                help_text="I have taken the denoted motor saw course already.",
                max_length=10,
                null=True,
                verbose_name="motor saw course",
            ),
        ),
        migrations.AlterField(
            model_name="drudge",
            name="place_of_citizenship_state",
            field=models.CharField(
                choices=[
                    ("AG", "AG"),
                    ("AI", "AI"),
                    ("AR", "AR"),
                    ("BS", "BS"),
                    ("BL", "BL"),
                    ("BE", "BE"),
                    ("FR", "FR"),
                    ("GE", "GE"),
                    ("GL", "GL"),
                    ("GR", "GR"),
                    ("JU", "JU"),
                    ("LU", "LU"),
                    ("NE", "NE"),
                    ("NW", "NW"),
                    ("OW", "OW"),
                    ("SH", "SH"),
                    ("SZ", "SZ"),
                    ("SO", "SO"),
                    ("SG", "SG"),
                    ("TG", "TG"),
                    ("TI", "TI"),
                    ("UR", "UR"),
                    ("VS", "VS"),
                    ("VD", "VD"),
                    ("ZG", "ZG"),
                    ("ZH", "ZH"),
                ],
                max_length=2,
                verbose_name="place of citizenship (canton)",
            ),
        ),
        migrations.AlterField(
            model_name="drudge",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="profile_images/",
                verbose_name="profile image",
            ),
        ),
        migrations.AlterField(
            model_name="specification",
            name="accomodation_free",
            field=models.CharField(
                choices=[("provided", "provided"), ("compensated", "compensated")],
                default="provided",
                max_length=20,
                verbose_name="accomodation on free days",
            ),
        ),
        migrations.AlterField(
            model_name="specification",
            name="accomodation_sick",
            field=models.CharField(
                choices=[("provided", "provided"), ("compensated", "compensated")],
                default="provided",
                max_length=20,
                verbose_name="accomodation on sick days",
            ),
        ),
        migrations.AlterField(
            model_name="specification",
            name="accomodation_working",
            field=models.CharField(
                choices=[("provided", "provided"), ("compensated", "compensated")],
                default="provided",
                max_length=20,
                verbose_name="accomodation on working days",
            ),
        ),
        migrations.AlterField(
            model_name="specification",
            name="breakfast_free",
            field=models.CharField(
                choices=[
                    ("no_compensation", "no compensation"),
                    ("at_accomodation", "at accomodation"),
                    ("external", "external"),
                ],
                default="no_compensation",
                max_length=20,
                verbose_name="breakfast on free days",
            ),
        ),
        migrations.AlterField(
            model_name="specification",
            name="breakfast_sick",
            field=models.CharField(
                choices=[
                    ("no_compensation", "no compensation"),
                    ("at_accomodation", "at accomodation"),
                    ("external", "external"),
                ],
                default="no_compensation",
                max_length=20,
                verbose_name="breakfast on sick days",
            ),
        ),
        migrations.AlterField(
            model_name="specification",
            name="breakfast_working",
            field=models.CharField(
                choices=[
                    ("no_compensation", "no compensation"),
                    ("at_accomodation", "at accomodation"),
                    ("external", "external"),
                ],
                default="no_compensation",
                max_length=20,
                verbose_name="breakfast on working days",
            ),
        ),
        migrations.AlterField(
            model_name="specification",
            name="clothing",
            field=models.CharField(
                choices=[("provided", "provided"), ("compensated", "compensated")],
                default="provided",
                max_length=20,
                verbose_name="clothing",
            ),
        ),
        migrations.AlterField(
            model_name="specification",
            name="conditions",
            field=models.FileField(
                blank=True, upload_to="conditions", verbose_name="conditions"
            ),
        ),
        migrations.AlterField(
            model_name="specification",
            name="lunch_free",
            field=models.CharField(
                choices=[
                    ("no_compensation", "no compensation"),
                    ("at_accomodation", "at accomodation"),
                    ("external", "external"),
                ],
                default="no_compensation",
                max_length=20,
                verbose_name="lunch on free days",
            ),
        ),
        migrations.AlterField(
            model_name="specification",
            name="lunch_sick",
            field=models.CharField(
                choices=[
                    ("no_compensation", "no compensation"),
                    ("at_accomodation", "at accomodation"),
                    ("external", "external"),
                ],
                default="no_compensation",
                max_length=20,
                verbose_name="lunch on sick days",
            ),
        ),
        migrations.AlterField(
            model_name="specification",
            name="lunch_working",
            field=models.CharField(
                choices=[
                    ("no_compensation", "no compensation"),
                    ("at_accomodation", "at accomodation"),
                    ("external", "external"),
                ],
                default="no_compensation",
                max_length=20,
                verbose_name="lunch on working days",
            ),
        ),
        migrations.AlterField(
            model_name="specification",
            name="supper_free",
            field=models.CharField(
                choices=[
                    ("no_compensation", "no compensation"),
                    ("at_accomodation", "at accomodation"),
                    ("external", "external"),
                ],
                default="no_compensation",
                max_length=20,
                verbose_name="supper on free days",
            ),
        ),
        migrations.AlterField(
            model_name="specification",
            name="supper_sick",
            field=models.CharField(
                choices=[
                    ("no_compensation", "no compensation"),
                    ("at_accomodation", "at accomodation"),
                    ("external", "external"),
                ],
                default="no_compensation",
                max_length=20,
                verbose_name="supper on sick days",
            ),
        ),
        migrations.AlterField(
            model_name="specification",
            name="supper_working",
            field=models.CharField(
                choices=[
                    ("no_compensation", "no compensation"),
                    ("at_accomodation", "at accomodation"),
                    ("external", "external"),
                ],
                default="no_compensation",
                max_length=20,
                verbose_name="supper on working days",
            ),
        ),
        migrations.DeleteModel(name="WaitList"),
    ]
