# Generated by Django 2.0.3 on 2018-03-07 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("zivinetz", "0002_auto_20180306_1808"),
    ]

    operations = [
        migrations.AddField(
            model_name="assessment",
            name="assignment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assessments",
                to="zivinetz.Assignment",
                verbose_name="assignment",
            ),
        ),
        migrations.AddField(
            model_name="assessment",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="created by",
            ),
        ),
    ]
