# Generated by Django 2.0.3 on 2018-03-13 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zivinetz', '0005_group_groupassignment'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='groupassignment',
            unique_together={('assignment', 'week')},
        ),
    ]
