# Generated by Django 2.0.3 on 2018-03-14 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("zivinetz", "0006_auto_20180313_1752")]

    operations = [
        migrations.AddField(
            model_name="scopestatement",
            name="default_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="zivinetz.Group",
                verbose_name="default group",
            ),
        )
    ]
