# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-18 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zivinetz', '0008_auto_20150416_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyholiday',
            name='applies_to',
            field=models.ManyToManyField(related_name='company_holidays', to='zivinetz.ScopeStatement', verbose_name='applies to scope statements'),
        ),
    ]
