# Generated by Django 2.1.2 on 2018-10-09 07:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("zivinetz", "0009_auto_20180314_1648")]

    operations = [
        migrations.AlterModelOptions(
            name="absence",
            options={
                "ordering": ["-days"],
                "verbose_name": "absence",
                "verbose_name_plural": "absences",
            },
        )
    ]
