# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-18 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zivinetz', '0009_companyholiday_applies_to'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specification',
            options={'ordering': ['ordering', 'scope_statement', 'with_accomodation'], 'verbose_name': 'specification', 'verbose_name_plural': 'specifications'},
        ),
        migrations.AddField(
            model_name='specification',
            name='ordering',
            field=models.IntegerField(default=0, verbose_name='ordering'),
        ),
    ]
