# Generated by Django 2.1.2 on 2018-10-12 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("zivinetz", "0010_auto_20181009_0934")]

    operations = [
        migrations.AddField(
            model_name="scopestatement",
            name="branch_no",
            field=models.CharField(
                default="20995", max_length=10, verbose_name="branch No."
            ),
            preserve_default=False,
        )
    ]
