# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-05 11:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zivinetz', '0010_auto_20160118_1625'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrudgeQuota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.DateField(verbose_name='week')),
                ('quota', models.PositiveIntegerField(verbose_name='quota')),
                ('scope_statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zivinetz.ScopeStatement', verbose_name='scope statement')),
            ],
            options={
                'verbose_name': 'drudge quota',
                'verbose_name_plural': 'drudge quotas',
            },
        ),
    ]
