# Generated by Django 2.1.2 on 2018-10-17 16:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("zivinetz", "0011_scopestatement_branch_no")]

    operations = [
        migrations.AlterField(
            model_name="scopestatement",
            name="branch_no",
            field=models.CharField(max_length=10, verbose_name="EIS No."),
        ),
        migrations.AlterField(
            model_name="scopestatement",
            name="eis_no",
            field=models.CharField(
                max_length=10, unique=True, verbose_name="scope statement No."
            ),
        ),
    ]
