# Generated by Django 2.2.24 on 2021-06-29 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zivinetz", "0012_auto_20181017_1842"),
    ]

    operations = [
        migrations.AlterField(
            model_name="absence",
            name="reason",
            field=models.CharField(
                choices=[
                    ("approved-vacation", "approved vacation"),
                    ("approved-holiday", "approved holiday"),
                    ("sick", "sick"),
                    ("motor-saw-course", "motor saw course"),
                    ("environment-course", "environment course"),
                    ("absenteeism", "absenteeism"),
                    ("missed-working-hours", "missed working hours"),
                ],
                max_length=20,
                verbose_name="reason",
            ),
        ),
    ]
