# Generated by Django 4.0.8 on 2023-01-31 08:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("zivinetz", "0015_remove_drudge_vegetarianism_alter_drudge_notes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="compensationset",
            name="spending_money",
        ),
    ]
