# Generated by Django 5.0.10 on 2025-01-23 12:42

from django.db import migrations


def create_user_profiles(apps, schema_editor):
    User = apps.get_model("auth", "User")
    UserProfile = apps.get_model("zivinetz", "UserProfile")

    for user in User.objects.all():
        # Skip if user already has a profile
        if UserProfile.objects.filter(user=user).exists():
            continue

        # If user is staff but not superuser, make them squad_leader
        if user.is_staff and not user.is_superuser:
            UserProfile.objects.create(user=user, user_type="squad_leader")
        # If user is superuser, make them admin
        elif user.is_superuser:
            UserProfile.objects.create(user=user, user_type="admin")
        # Everyone else is a drudge
        else:
            UserProfile.objects.create(user=user, user_type="drudge")


def reverse_user_profiles(apps, schema_editor):
    UserProfile = apps.get_model("zivinetz", "UserProfile")
    UserProfile.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("zivinetz", "0019_userprofile"),  # Reference your previous migration
    ]

    operations = [
        migrations.RunPython(create_user_profiles, reverse_user_profiles),
    ]
