# Generated by Django 5.0.9 on 2025-07-07 11:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zivinetz", "0020_create_user_profiles"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="drudge",
            name="source_other",
        ),
        migrations.AlterField(
            model_name="drudge",
            name="source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Social Media", "Social Media"),
                    ("Freunde/Familie/Bekannte", "Freunde/Familie/Bekannte"),
                    ("Internetsuche", "Internetsuche"),
                    ("E-Zivi", "E-Zivi"),
                    ("Plakat/Flyer", "Plakat/Flyer"),
                    (
                        "Fahrzeug oder Einsatzgruppe gesehen",
                        "Fahrzeug oder Einsatzgruppe gesehen",
                    ),
                ],
                max_length=100,
                verbose_name="Wie hast du vom Naturnetz erfahren?",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("drudge", "Drudge"),
                    ("squad_leader", "Squad Leader"),
                    ("user_plus", "User Plus"),
                    ("admin", "Admin"),
                    ("dev_admin", "DEV-Admin"),
                ],
                default="drudge",
                max_length=20,
            ),
        ),
    ]
