# Generated by Django 5.0.14 on 2025-11-28 15:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zivinetz", "0021_remove_drudge_source_other_alter_drudge_source_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobReferenceAuthor",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location", models.CharField(max_length=100, verbose_name="location")),
                (
                    "full_name",
                    models.CharField(max_length=100, verbose_name="full name"),
                ),
                ("function", models.CharField(max_length=100, verbose_name="function")),
            ],
            options={
                "verbose_name": "job reference author",
                "verbose_name_plural": "job reference authors",
                "ordering": ["full_name"],
            },
        ),
        migrations.AddField(
            model_name="jobreference",
            name="author_full_name",
            field=models.CharField(
                default="Dr. Marco Sacchi", max_length=100, verbose_name="full name"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="jobreference",
            name="author_function",
            field=models.CharField(
                default="Geschäftsführer", max_length=100, verbose_name="function"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="jobreference",
            name="author_location",
            field=models.CharField(
                default="Kloster Fahr", max_length=100, verbose_name="location"
            ),
            preserve_default=False,
        ),
    ]
